Adiciona spider para Paulínia-SP
trevineju/querido-diario pull request #14
Opened 2023-04-28 21:25 UTC by trevineju

**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [ ] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [x] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [ ] Você verificou que não existe nenhum erro nos logs (`log/ERROR` igual a zero).
- [x] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [x] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

<Descreva o seu Pull Request informando a issue (caso exista) que está sendo solucionada ou uma descrição do código apresentado>

2023-05-02 23:15 UTC, trevineju commented on data_collection/gazette/spiders/sp_paulinia.py
> +            year_to_scrape = int(year.xpath("./a/text()").get())
antes: `year_to_scrape = int(year.xpath("./a/font/text()").get())` 

não coletava o ano direito

2023-05-02 23:23 UTC, trevineju commented on data_collection/gazette/spiders/sp_paulinia.py
> +                continue  # pular a iteração atual
antes era: 
``` python
            if (
                year_to_scrape < self.start_date.year
                or year_to_scrape == datetime.date.today().year
            ):
                continue
```

Com a linha que tem o `==` sendo pra evitar uma requisição a mais. Ainda não entendi pq. 
E não estava filtrando por data corretamente já que não incluia ano do end_date.

2023-05-02 23:26 UTC, trevineju commented on data_collection/gazette/spiders/sp_paulinia.py
> +                continue
antes: não existia as linhas 54 e 55. Adicionadas pra funcionarem com raspagem de intervalos definidos (antes, na linha 22, apenas o ano é validado como dentro do intervalo, aqui valida dia e mês também)

2023-07-07 13:10 UTC, ogecece requested changes

2023-07-07 13:10 UTC, ogecece commented on data_collection/gazette/spiders/sp_paulinia.py
> +        )
Podemos substituir por seletor CSS e vai ficar melhor de lidar com as classes
```suggestion
        editions = response.css("div.body-content div.row a[href*='AbreSemanario']")
```

2023-08-18 17:43 UTC, merged